colors:
    light:
        $name: Light
        $description: All the properties below are when the website is on light mode
        background_main:
            $name: Background main
            $description: Main background color of the blog
            $type: color
        background_secondary:
            $name: Background secondary
            $description: Secondary background color of the blog
            $type: color
        background_contrast:
            $name: Background contrast
            $description: Background contrast color of the blog
            $type: color
        background_overlay:
            $name: Background overlay
            $description: Background overlay color of the blog
            $type: color
        content_lead:
            $name: Content lead
            $description: Lead color of the content of the blog
            $type: color
        content_main:
            $name: Content main
            $description: Main color of the content of the blog
            $type: color
        content_secondary:
            $name: Content secondary
            $description: Secondary color of the content of the blog
            $type: color

    dark:
        $name: Dark
        $description: All the properties below are when the website is on dark mode
        background_main:
            $name: Background main
            $description: Main background color of the blog
            $type: color
        background_secondary:
            $name: Background secondary
            $description: Secondary background color of the blog
            $type: color
        background_contrast:
            $name: Background contrast
            $description: Background contrast color of the blog
            $type: color
        background_overlay:
            $name: Background overlay
            $description: Background overlay color of the blog
            $type: color
        content_lead:
            $name: Content lead
            $description: Lead color of the content of the blog
            $type: color
        content_main:
            $name: Content main
            $description: Main color of the content of the blog
            $type: color
        content_secondary:
            $name: Content secondary
            $description: Secondary color of the content of the blog
            $type: color

fonts:
    family_primary:
        $name: Font Primary
        $description: Main font of the blog
        $type: font
    family_secondary:
        $name: Font Secondary
        $description: Secondary font of the blog
        $type: font
    color_primary:
        $name: Color Primary
        $description: Main font color of the blog
        $type: color
