THEME_NAME: default
THEME_VERSION: 1.0.0
POSTS_PER_PAGINATION: 10

colors:
  accent: "#896c6b"
  light:
    background_body: "#fffaf8"
    background_box: "#ffffff"
    background_contrast: "#E1E3E6"
    text_content: "#000000"
    text_content_secondary: "#777"
  dark:
    background_body: "#0a0a0a"
    background_box: "#222222"
    background_contrast: "#666666"
    text_content: "#ffffff"
    text_content_secondary: "#ffffff"

font:
  size: 16
  family: "Nunito, sans-serif"

line_height: 24

box:
  radius: 20
  shadow: "0 0 30px rgba(0,0,0,0.05)"

show_post_featured_image: true