theme_version: 1.0

colors:
  accent: "#896c6b"
  light:
    background_body: "#fffaf8"
    background_box: "#ffffff"
    background_contrast: "#E1E3E6"
    text_content: "#000000"
    text_content_secondary: "#777"

font:
  size: 16
  family: "Nunito, sans-serif"

line_height: 24

box:
  radius: 20
  shadow: "0 0 30px rgba(0,0,0,0.05)"

show_post_featured_image: true
